### ISSUE TITLE
exception during compilation.

### ISSUE THREAD

**Issue by kanchankjha** [treelogic-swe/aws-mock#43]
ubuntu@ise-sys-lnx1:~/project/tools/aws-mock$ sudo gradle jettyRun
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/2.10/userguide/gradle_daemon.html.
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jettyRun
failed org.gradle.api.plugins.jetty.internal.JettyPluginWebAppContext@57096b18{/aws-mock,/home/ubuntu/project/tools/aws-mock/src/main/webapp}: java.lang.NoClassDefFoundError: org/apache/tomcat/PeriodicEventListener
failed ContextHandlerCollection@44767b64: java.lang.NoClassDefFoundError: org/apache/tomcat/PeriodicEventListener
failed HandlerCollection@63907b4d: java.lang.NoClassDefFoundError: org/apache/tomcat/PeriodicEventListener
Error starting handlers
java.lang.NoClassDefFoundError: org/apache/tomcat/PeriodicEventListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)

<<<snip>>>

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.PeriodicEventListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 126 more
> Building 75% > :jettyRun > Running at http://localhost:8000/aws-mock

**Comment by nottoseethesun** [comment]
We have a fix coming up for this and hope to provide details soon.

**Comment by maxiaohao** [comment]
Hi kanchankjha, 
Not sure why in your log `org.apache.tomcat.PeriodicEventListener` was referred as aws-mock doesn't refer to that tomcat class as I know.
Please try updating your gradle to the latest version (`3.4.1`, download the release from https://gradle.org/releases). The jettyRun task works with either gradle `3.4.1` or `2.14.1` for me, on Oracle JDK 1.8.0. 
Thanks.

**Comment by kanchankjha** [comment]
thanks maxiaohao.

changing gradle version helped. but now its stuck at 75%.

ubuntu@ise-sys-lnx1:~/project/tools/aws-mock$ ../gradle-3.4.1/bin/gradle jettyRun
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> Configuring > 0/2 projects > root project > Resolving dependencies ':classpath'^C
ubuntu@ise-sys-lnx1:~/project/tools/aws-mock$ 
ubuntu@ise-sys-lnx1:~/project/tools/aws-mock$ 
ubuntu@ise-sys-lnx1:~/project/tools/aws-mock$ 
ubuntu@ise-sys-lnx1:~/project/tools/aws-mock$ sudo ../gradle-3.4.1/bin/gradle jettyRun
[sudo] password for ubuntu: 
Starting a Gradle Daemon (subsequent builds will be faster)
The Jetty plugin has been deprecated and is scheduled to be removed in Gradle 4.0. Consider using the Gretty (https://github.com/akhikhl/gretty) plugin instead.
        at build_al4ghralpft0j6iicz0ao23xd.run(/home/ubuntu/project/tools/aws-mock/build.gradle:19)
Cleaned up directory '/home/ubuntu/project/tools/aws-mock/build/classes/main'
Cleaned up directory '/home/ubuntu/project/tools/aws-mock/build/resources/main'
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:processResources
:classes
:jettyRun
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ubuntu/project/tools/gradle-3.4.1/lib/gradle-logging-3.4.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.5/6edffc576ce104ec769d954618764f39f0f0f10d/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[2017-04-05 14:31:28,582] [WARN ] [Daemon worker] properties file 'aws-mock.properties' not found in classpath, no default property in 'aws-mock-default.properties' will be overridden (com.tlswe.awsmock.common.util.PropertiesUtils.java:75)
[2017-04-05 14:31:28,712] [INFO ] [Daemon worker] aws-mock started. (com.tlswe.awsmock.common.listener.AppServletContextListener.java:75)
> Building 75% > :jettyRun > Running at http://localhost:8000/aws-mock

**Comment by maxiaohao** [comment]
Hi, 
That's exactly the correct output (the jetty server is not forked into a new proc though, Ctrl+C would stop it). Now aws-mock is running on localhost:8000 and you can use the EC2 client tool or AWS EC2 API tool to access it:)

**Comment by maxiaohao** [comment]
Alternatively, you may `gradle clean war` to make a war file and drop it into a servlet container such as tomcat.

**Comment by nottoseethesun** [comment]
Looks like this is resolved, so closing.
